#!/bin/sh
#
#  Host Profile Overlay FS bash driver for X11
#  Copyright (C) 2011 Andrei Warkentin <andreiw@vmware.com>
#
#  This program can be distributed under the terms of the GNU GPL.
#  See the file COPYING.
#
#  Using: Edit and place into home directory as .xprofile.
#

hpfs=~/bin/hpfs
redir=~/profiles/$(hostname)
do_mount=1

if [ ! -d $redir ]
then
    if [ -e $redir ]
    then
        echo "$redir is not a directory, please fix me"
        do_mount=0
    fi
    echo Creating new profile $redir
    mkdir -p $redir
fi

if [ -f $redir/.hpfs_no_redirect ]
then
    echo "$redir/.hpfs_no_redirect exists"
    do_mount=0
fi

if [ $do_mount -eq 0 ]
then
    echo "skipping host profile redirection"
else
    while true
    do
        if [ ! ~/.bash_profile -ot $redir/.bash_profile ] &&
            [ ! ~/.bash_profile -nt $redir/.bash_profile ]
        then
            echo "host profile redirection already present"
            break
        fi

        mkdir $redir/.hpfslock &>/dev/null
        if [ $? -eq 0 ]
        then
            echo "enabling host profile redirection"

            #
            # If you want root to be able to see
            # your files, you need to add allow_root,
            # although this means changing the system-wide
            # FUSE configuration as well.
            #
            $hpfs ~/ $redir -o nonempty
            rmdir $redir/.hpfslock &>/dev/null
            break
        else
            echo "retry ($redir/.hpfslock exists)"
            sleep .5
            continue
        fi
    done
fi
